version = 1

[[annotations]]
path = ["**.qrc", "**CMakeLists.txt", ".cmake.conf", "**.yaml",
        "**.json", "**.cmake", ".tag", "**/.gitattributes",
        "**.gitignore"]
precedence = "closest"
comment = "build system"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["**.qdocconf"]
comment = "documentation"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

[[annotations]]
path = ["src/languageserver/3rdparty/specification.md"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) Microsoft Corporation."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ["**.toml", "licenseRule.json"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "LicenseRef-Qt-Commercial OR GFDL-1.3-no-invariants-only"

